CREATE TABLE [dbo].[Prospect] (
    [ID]               INT              NOT NULL,
    [ProspectType]     NVARCHAR (20)    NOT NULL,
    [FirstName]        NVARCHAR (50)    NULL,
    [LastName]         NVARCHAR (50)    NULL,
    [MiddleName]       NVARCHAR (50)    NULL,
    [PrefixName]       NVARCHAR (20)    NULL,
    [SuffixName]       NVARCHAR (50)    NULL,
    [FullName]         NVARCHAR (100)   NULL,
    [HomePhoneNumber]        NVARCHAR (20)    NULL,
    [WorkPhoneNumber]      NVARCHAR (20)    NULL,
	[OtherPhoneNumber]      NVARCHAR (20)    NULL,
    [HomeEmailAddress]     NVARCHAR (100)   NULL,
	[WorkEmailAddress]     NVARCHAR (100)   NULL,
	[OtherEmailAddress]     NVARCHAR (100)   NULL,
    [HomeStreet]           NVARCHAR (100)   NULL,
    [HomeApartment]        NVARCHAR (100)   NULL,
    [HomeCity]             NVARCHAR (100)   NULL,
    [HomeStateCode]        NVARCHAR (10)    NULL,
    [HomeZip]              NVARCHAR (20)    NULL,
    [HomeCountryCode]      NVARCHAR (10)    NULL,
    [WorkStreet]           NVARCHAR (100)   NULL,
    [WorkApartment]        NVARCHAR (100)   NULL,
    [WorkCity]             NVARCHAR (100)   NULL,
    [WorkStateCode]        NVARCHAR (10)    NULL,
    [WorkZip]              NVARCHAR (20)    NULL,
    [WorkCountryCode]      NVARCHAR (10)    NULL,
    [OtherStreet]           NVARCHAR (100)   NULL,
    [OtherApartment]        NVARCHAR (100)   NULL,
    [OtherCity]             NVARCHAR (100)   NULL,
    [OtherStateCode]        NVARCHAR (10)    NULL,
    [OtherZip]              NVARCHAR (20)    NULL,
    [OtherCountryCode]      NVARCHAR (10)    NULL,
    [Status]           NVARCHAR (20)    NOT NULL,
    [Converted]        NVARCHAR (1)     NOT NULL,
    [CreatedBy]        NVARCHAR (50)    NOT NULL,
    [CreatedDate]      DATETIME         NOT NULL,
    [UpdatedBy]        NVARCHAR (50)    NULL,
    [UpdatedDate]      DATETIME         NULL,
    [RowVersionNumber] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Prospect_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

