CREATE TABLE [dbo].[Prospect] (
    [ID]               INT              NOT NULL,
    [ProspectType]     NVARCHAR (20)    NOT NULL,
    [FirstName]        NVARCHAR (50)    NULL,
    [LastName]         NVARCHAR (50)    NULL,
    [MiddleName]       NVARCHAR (50)    NULL,
    [PrefixName]       NVARCHAR (20)    NULL,
    [SuffixName]       NVARCHAR (50)    NULL,
    [FullName]         NVARCHAR (100)   NULL,
    [PhoneType]        NVARCHAR (20)    NULL,
    [PhoneNumber]      NVARCHAR (20)    NULL,
    [EmailType]        NVARCHAR (20)    NULL,
    [EmailAddress]     NVARCHAR (100)   NULL,
    [AddressType]      NVARCHAR (20)    NULL,
    [Street]           NVARCHAR (100)   NULL,
    [Apartment]        NVARCHAR (100)   NULL,
    [City]             NVARCHAR (100)   NULL,
    [StateCode]        NVARCHAR (10)    NULL,
    [Zip]              NVARCHAR (20)    NULL,
    [CountryCode]      NVARCHAR (10)    NULL,
    [Status]           NVARCHAR (20)    NOT NULL,
    [Converted]        NVARCHAR (1)     NOT NULL,
    [CreatedBy]        NVARCHAR (50)    NOT NULL,
    [CreatedDate]      DATETIME         NOT NULL,
    [UpdatedBy]        NVARCHAR (50)    NULL,
    [UpdatedDate]      DATETIME         NULL,
    [RowVersionNumber] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Prospect_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

